catalogMode: prefer

shellEmulator: true

trustPolicy: no-downgrade

overrides:
  axios@>=1.0.0 <1.12.0: '>=1.12.0'
  axios@>=1.0.0 <1.8.2: '>=1.8.2'
  esbuild@<=0.24.2: '>=0.25.0'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'

catalog:
  '@antfu/eslint-config': ^6.6.1
  '@arcjet/next': ^1.0.0-beta.15
  '@chromatic-com/playwright': ^0.12.8
  '@clerk/localizations': ^3.30.1
  '@clerk/nextjs': ^6.36.2
  '@clerk/types': ^4.101.6
  '@commitlint/cli': ^20.2.0
  '@commitlint/config-conventional': ^20.2.0
  '@commitlint/prompt-cli': ^20.2.0
  '@commitlint/types': ^20.2.0
  '@electric-sql/pglite-socket': ^0.0.19
  '@eslint-react/eslint-plugin': ^2.3.13
  '@faker-js/faker': ^10.1.0
  '@hookform/resolvers': ^5.2.2
  '@logtape/logtape': ^1.2.2
  '@next/bundle-analyzer': ^16.0.10
  '@next/eslint-plugin-next': ^16.0.10
  '@playwright/test': ^1.57.0
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-slot': ^1.2.4
  '@sentry/nextjs': ^10.30.0
  '@spotlightjs/spotlight': ^4.8.0
  '@supabase/supabase-js': ^2.87.1
  '@t3-oss/env-nextjs': ^0.13.8
  '@tailwindcss/postcss': ^4.1.18
  '@types/node': ^24.10.3
  '@types/pg': ^8.16.0
  '@types/react': ^19.2.7
  '@types/showdown': ^2.0.6
  '@vercel/analytics': ^1.6.1
  '@vercel/speed-insights': ^1.3.1
  '@vitejs/plugin-react': ^5.1.2
  '@vitest/browser': ^4.0.15
  '@vitest/browser-playwright': ^4.0.15
  '@vitest/coverage-v8': ^4.0.15
  babel-plugin-react-compiler: ^1.0.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  conventional-changelog-conventionalcommits: ^9.1.0
  cross-env: ^10.1.0
  drizzle-kit: ^0.31.8
  drizzle-orm: ^0.45.1
  eslint: ^9.39.2
  eslint-plugin-format: ^1.1.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-playwright: ^2.4.0
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.24
  eslint-plugin-tailwindcss: ^4.0.0-beta.0
  framer-motion: ^12.23.26
  geist: ^1.5.1
  jiti: ^2.6.1
  knip: ^5.73.4
  lefthook: ^2.0.11
  lucide-react: ^0.561.0
  next: ^16.0.10
  next-intl: ^4.6.0
  next-themes: ^0.4.6
  npm-run-all: ^4.1.5
  pg: ^8.16.3
  postcss: ^8.5.6
  postcss-load-config: ^6.0.1
  posthog-js: ^1.306.1
  react: ^19.2.3
  react-dom: ^19.2.3
  react-hook-form: ^7.68.0
  react-markdown: ^10.1.0
  rimraf: ^6.1.2
  semantic-release: ^21.1.2
  server-only: ^0.0.1
  showdown: ^2.1.0
  svix: ^1.82.0
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.17
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  vite: ^7.2.7
  vite-tsconfig-paths: ^5.1.4
  vitest: ^4.0.4
  vitest-browser-react: ^2.0.2
  zod: ^4.1.13
