catalogMode: prefer

shellEmulator: true

trustPolicy: no-downgrade
overrides:
  axios@>=1.0.0 <1.12.0: '>=1.12.0'
  axios@>=1.0.0 <1.8.2: '>=1.8.2'
  esbuild@<=0.24.2: '>=0.25.0'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'

catalog:
  '@antfu/eslint-config': ^6.7.3
  '@arcjet/next': ^1.0.0-beta.15
  '@clerk/localizations': ^3.32.1
  '@clerk/nextjs': ^6.36.5
  '@clerk/types': ^4.101.9
  '@commitlint/cli': ^20.2.0
  '@commitlint/config-conventional': ^20.2.0
  '@commitlint/prompt-cli': ^20.2.0
  '@commitlint/types': ^20.2.0
  '@electric-sql/pglite-socket': ^0.0.19
  '@eslint-react/eslint-plugin': ^2.5.0
  '@faker-js/faker': ^10.1.0
  '@hookform/resolvers': ^5.2.2
  '@logtape/logtape': ^1.3.5
  '@next/bundle-analyzer': ^16.1.1
  '@next/eslint-plugin-next': ^16.1.1
  '@playwright/test': ^1.57.0
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-slot': ^1.2.4
  '@sentry/nextjs': ^10.32.1
  '@spotlightjs/spotlight': ^4.9.0
  '@supabase/supabase-js': ^2.89.0
  '@t3-oss/env-nextjs': ^0.13.10
  '@tailwindcss/postcss': ^4.1.18
  '@types/node': ^24.10.4
  '@types/pg': ^8.16.0
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@types/showdown': ^2.0.6
  '@vercel/analytics': ^1.6.1
  '@vercel/speed-insights': ^1.3.1
  '@vitejs/plugin-react': ^5.1.2
  '@vitest/browser': ^4.0.16
  '@vitest/browser-playwright': ^4.0.16
  '@vitest/coverage-v8': ^4.0.16
  agentation: ^1.3.2
  babel-plugin-react-compiler: ^1.0.0
  chalk: ^5.6.2
  chrome-launcher: ^1.2.1
  class-variance-authority: ^0.7.1
  cli-table3: ^0.6.5
  clsx: ^2.1.1
  commander: ^14.0.3
  conventional-changelog-conventionalcommits: ^9.1.0
  cross-env: ^10.1.0
  dotenv: ^17.2.4
  drizzle-kit: ^0.31.8
  drizzle-orm: ^0.45.1
  esbuild: ^0.27.2
  eslint: ^9.39.2
  eslint-plugin-format: ^1.1.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-playwright: ^2.4.0
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.26
  eslint-plugin-tailwindcss: ^4.0.0-beta.0
  framer-motion: ^12.23.26
  geist: ^1.5.1
  jiti: ^2.6.1
  knip: ^5.78.0
  lefthook: ^2.0.13
  lighthouse: ^13.0.3
  lucide-react: ^0.562.0
  next: ^16.1.1
  next-intl: ^4.6.1
  next-themes: ^0.4.6
  npm-run-all: ^4.1.5
  pg: ^8.16.3
  postcss: ^8.5.6
  postcss-load-config: ^6.0.1
  posthog-js: ^1.312.0
  react: ^19.2.3
  react-dom: ^19.2.3
  react-hook-form: ^7.69.0
  react-markdown: ^10.1.0
  rimraf: ^6.1.2
  semantic-release: ^21.1.2
  server-only: ^0.0.1
  showdown: ^2.1.0
  svix: ^1.84.1
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.17
  tsx: ^4.21.0
  typescript: ^5.9.3
  vite: ^7.3.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^4.0.16
  vitest-browser-react: ^2.0.2
  zod: ^4.3.4
