catalogMode: prefer

shellEmulator: true

trustPolicy: no-downgrade
overrides:
  axios@>=1.0.0 <1.12.0: '>=1.12.0'
  axios@>=1.0.0 <1.8.2: '>=1.8.2'
  esbuild@<=0.24.2: '>=0.25.0'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'

catalog:
  '@antfu/eslint-config': ^6.7.3
  '@arcjet/next': ^1.0.0-beta.15
  '@clerk/localizations': ^3.35.3
  '@clerk/nextjs': ^6.37.1
  '@clerk/types': ^4.101.14
  '@commitlint/cli': ^20.4.0
  '@commitlint/config-conventional': ^20.4.0
  '@commitlint/prompt-cli': ^20.4.0
  '@commitlint/types': ^20.4.0
  '@electric-sql/pglite-socket': ^0.0.20
  '@eslint-react/eslint-plugin': ^2.8.4
  '@faker-js/faker': ^10.2.0
  '@hookform/resolvers': ^5.2.2
  '@logtape/logtape': ^1.3.7
  '@next/bundle-analyzer': ^16.1.6
  '@next/eslint-plugin-next': ^16.1.6
  '@playwright/test': ^1.58.1
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-slot': ^1.2.4
  '@sentry/nextjs': ^10.38.0
  '@spotlightjs/spotlight': ^4.10.0
  '@supabase/supabase-js': ^2.93.3
  '@t3-oss/env-nextjs': ^0.13.10
  '@tailwindcss/postcss': ^4.1.18
  '@types/node': ^24.10.9
  '@types/pg': ^8.16.0
  '@types/react': ^19.2.10
  '@types/react-dom': ^19.2.3
  '@types/showdown': ^2.0.6
  '@vercel/analytics': ^1.6.1
  '@vercel/speed-insights': ^1.3.1
  '@vitejs/plugin-react': ^5.1.2
  '@vitest/browser': ^4.0.18
  '@vitest/browser-playwright': ^4.0.18
  '@vitest/coverage-v8': ^4.0.18
  agentation: ^1.3.2
  babel-plugin-react-compiler: ^1.0.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  conventional-changelog-conventionalcommits: ^9.1.0
  cross-env: ^10.1.0
  drizzle-kit: ^0.31.8
  drizzle-orm: ^0.45.1
  esbuild: ^0.27.2
  eslint: ^9.39.2
  eslint-plugin-format: ^1.3.1
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-playwright: ^2.5.1
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.5.0
  eslint-plugin-tailwindcss: ^4.0.0-beta.0
  framer-motion: ^12.29.2
  geist: ^1.5.1
  jiti: ^2.6.1
  knip: ^5.82.1
  lefthook: ^2.0.16
  lucide-react: ^0.563.0
  next: ^16.1.6
  next-intl: ^4.8.1
  next-themes: ^0.4.6
  npm-run-all: ^4.1.5
  pg: ^8.18.0
  postcss: ^8.5.6
  postcss-load-config: ^6.0.1
  posthog-js: ^1.336.4
  react: ^19.2.4
  react-dom: ^19.2.4
  react-hook-form: ^7.71.1
  react-markdown: ^10.1.0
  rimraf: ^6.1.2
  semantic-release: ^21.1.2
  server-only: ^0.0.1
  showdown: ^2.1.0
  svix: ^1.84.1
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.17
  typescript: ^5.9.3
  vite: ^7.3.1
  vite-tsconfig-paths: ^5.1.4
  vitest: ^4.0.18
  vitest-browser-react: ^2.0.5
  zod: ^4.3.6
